import { FileText, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { HoverCard, HoverCardContent, HoverCardTrigger } from "@/components/ui/hover-card";
import { TierBadge } from "./tier-badge";
import { cn } from "@/lib/utils";
import { TIER_CONFIG, type RiskTier } from "@/pages/admin/constants";

type Props = {
  companyName: string;
  tier: RiskTier | null | undefined;
  riskScore: number | null | undefined;
  factors?: string[];
  employees: number;
  spouses: number;
  children: number;
  totalLives: number;
  censusId: string;
  submittedAt?: Date | string | null;
  onViewCensus?: () => void;
};

export function GroupHeader({
  companyName,
  tier,
  riskScore,
  factors,
  employees,
  spouses,
  children,
  totalLives,
  censusId,
  submittedAt,
  onViewCensus,
}: Props) {
  const shortId = `KBA-${censusId.slice(0, 8).toUpperCase()}`;
  const submitted =
    submittedAt instanceof Date
      ? submittedAt
      : submittedAt
        ? new Date(submittedAt)
        : null;
  const submittedLabel = submitted
    ? submitted.toLocaleDateString("en-US", {
        month: "short",
        day: "numeric",
        year: "numeric",
      })
    : null;

  const tierConfig = tier && TIER_CONFIG[tier];

  return (
    <div className="mb-6" data-testid="proposal-group-header">
      <div className="mb-3 flex flex-wrap items-center gap-3">
        <TierBadge tier={tier} />
        {riskScore != null && tierConfig && (
          <HoverCard openDelay={120} closeDelay={100}>
            <HoverCardTrigger asChild>
              <button
                type="button"
                className="inline-flex items-center gap-1.5 rounded-full border bg-card px-2.5 py-0.5 text-[11px] font-semibold tabular-nums transition hover-elevate"
                data-testid="badge-risk-score"
              >
                <Sparkles className="h-3 w-3" style={{ color: tierConfig.hsl }} />
                <span className="text-muted-foreground">Kennion Score</span>
                <span style={{ color: tierConfig.hsl }}>{riskScore.toFixed(2)}</span>
              </button>
            </HoverCardTrigger>
            <HoverCardContent className="w-[340px] p-0" align="start">
              <div
                className="rounded-t-md px-4 py-2.5"
                style={{ background: tierConfig.hsl, color: "white" }}
              >
                <div className="text-[10px] font-semibold uppercase tracking-[0.14em] opacity-85">
                  Underwriting summary
                </div>
                <div className="mt-0.5 flex items-baseline gap-2">
                  <div className="text-2xl font-bold tabular-nums leading-tight">
                    {riskScore.toFixed(2)}
                  </div>
                  <div className="text-xs opacity-90">{tierConfig.label}</div>
                </div>
              </div>
              <div className="px-4 py-3">
                <p className="text-xs leading-relaxed text-muted-foreground">
                  Generated by our AI underwriting engine from your census demographics, family
                  composition, and group size.
                </p>
                {factors && factors.length > 0 && (
                  <ul className="mt-3 space-y-1.5">
                    {factors.map((f, i) => (
                      <li key={i} className="flex items-start gap-2 text-xs leading-relaxed">
                        <span
                          className="mt-1.5 h-1 w-1 shrink-0 rounded-full"
                          style={{ background: tierConfig.hsl }}
                          aria-hidden
                        />
                        <span>{f}</span>
                      </li>
                    ))}
                  </ul>
                )}
              </div>
            </HoverCardContent>
          </HoverCard>
        )}
      </div>
      <h1
        className="text-[34px] font-bold leading-tight tracking-tight text-foreground"
        data-testid="text-group-title"
      >
        {companyName}
      </h1>

      <div className="mt-3 flex flex-wrap items-center justify-between gap-3">
        <div className="flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-muted-foreground">
          <span
            className="font-mono font-semibold tracking-wide text-foreground"
            data-testid="text-census-id"
          >
            Census {shortId}
          </span>
          {submittedLabel && (
            <>
              <span aria-hidden>·</span>
              <span data-testid="text-submitted-at">Submitted {submittedLabel}</span>
            </>
          )}
        </div>
        {onViewCensus && (
          <Button
            variant="outline"
            size="sm"
            onClick={onViewCensus}
            className="gap-1.5"
            data-testid="button-view-census"
          >
            <FileText className="h-3.5 w-3.5" />
            View Census
          </Button>
        )}
      </div>

      <div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-4">
        <Stat label="Employees" value={employees} testId="stat-employees" />
        <Stat label="Spouses" value={spouses} testId="stat-spouses" />
        <Stat label="Children" value={children} testId="stat-children" />
        <Stat label="Total Lives" value={totalLives} emphasis testId="stat-total-lives" />
      </div>
    </div>
  );
}

function Stat({
  label,
  value,
  emphasis,
  testId,
}: {
  label: string;
  value: number;
  emphasis?: boolean;
  testId?: string;
}) {
  return (
    <Card className={cn("p-3", emphasis && "border-primary/40 bg-primary/5")} data-testid={testId}>
      <div className="text-[10px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">
        {label}
      </div>
      <div className="mt-0.5 text-xl font-bold tabular-nums">{value ?? 0}</div>
    </Card>
  );
}
